- params:
    git:
      repoName: npm-test
      branches:
        - main
    scan:
      includeAllVulnerabilities: true
      projects:
        - installCommand: npm i
    jfrogPlatform:
      jfrogProjectKey: 